### ISSUE TITLE
[Crash]: Game crahes while looking at a map in an item frame

### ISSUE THREAD

**Issue by Cape-City** [melontini/m-tweaks#21]
### What happened?

If the mod Map Tooltip also is active and you are looking at a map in an item frame, the game crashes. If only one of the mods is running, everything is fine. Having a map in on or off-hand also is no problem. I you disable the item frame tooltip within the config of m-tweaks, the issue is also gone. With item frames, which have other items shown, the issue does not happens either.

https://www.curseforge.com/minecraft/mc-mods/map-tooltip
-> maptooltip-fabric-1.19-2.0.1.jar

### Logs

[21:24:01] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.19
[21:24:01] [main/INFO]: Loading 65 mods:
	- cloth-config 9.0.94
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.76.1+1.19.3
	   |-- fabric-api-base 0.4.21+70be179c85
	   |-- fabric-api-lookup-api-v1 1.6.20+49abcf7e85
	   |-- fabric-biome-api-v1 12.1.2+f1c68e5885
	   |-- fabric-block-api-v1 1.0.5+e022e5d185
	   |-- fabric-blockrenderlayer-v1 1.1.31+928d44d585
	   |-- fabric-client-tags-api-v1 1.0.12+1134c5b885
	   |-- fabric-command-api-v1 1.2.23+f71b366f85
	   |-- fabric-command-api-v2 2.2.2+2961b4a085
	   |-- fabric-commands-v0 0.2.40+df3654b385
	   |-- fabric-containers-v0 0.1.47+df3654b385
	   |-- fabric-content-registries-v0 3.5.3+1d37d50285
	   |-- fabric-convention-tags-v1 1.3.0+521b5c5285
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebe85
	   |-- fabric-data-generation-api-v1 11.3.3+40dc7a9485
	   |-- fabric-dimensions-v1 2.1.42+00a2eb1085
	   |-- fabric-entity-events-v1 1.5.7+b83334a085
	   |-- fabric-events-interaction-v0 0.4.40+3baeb27a85
	   |-- fabric-events-lifecycle-v0 0.2.45+df3654b385
	   |-- fabric-game-rule-api-v1 1.0.30+99f9db8085
	   |-- fabric-item-api-v1 2.1.11+71b8257385
	   |-- fabric-item-group-api-v1 2.1.14+b5470ac785
	   |-- fabric-key-binding-api-v1 1.0.31+bc01e09785
	   |-- fabric-keybindings-v0 0.2.29+df3654b385
	   |-- fabric-lifecycle-events-v1 2.2.10+23a79c8a85
	   |-- fabric-loot-api-v2 1.1.22+75e9821185
	   |-- fabric-loot-tables-v1 1.1.26+9e7660c685
	   |-- fabric-message-api-v1 5.1.0+c85585f885
	   |-- fabric-mining-level-api-v1 2.1.33+49abcf7e85
	   |-- fabric-models-v0 0.3.27+11ba9c3b85
	   |-- fabric-networking-api-v1 1.2.17+4017a8cb85
	   |-- fabric-networking-v0 0.3.34+df3654b385
	   |-- fabric-object-builder-api-v1 5.4.3+eb2a3ba985
	   |-- fabric-particles-v1 1.0.20+f1e4495b85
	   |-- fabric-recipe-api-v1 1.0.1+5176f73d85
	   |-- fabric-registry-sync-v0 2.1.0+f7b4d36485
	   |-- fabric-renderer-api-v1 2.2.2+3a95925a85
	   |-- fabric-renderer-indigo 0.8.0+3a95925a85
	   |-- fabric-renderer-registries-v1 3.2.31+df3654b385
	   |-- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85
	   |-- fabric-rendering-fluids-v1 3.0.18+f1e4495b85
	   |-- fabric-rendering-v0 1.1.34+df3654b385
	   |-- fabric-rendering-v1 1.13.0+ad17775585
	   |-- fabric-resource-conditions-api-v1 2.3.0+e63306e085
	   |-- fabric-resource-loader-v0 0.11.1+b93ffe4d85
	   |-- fabric-screen-api-v1 1.0.41+f1e4495b85
	   |-- fabric-screen-handler-api-v1 1.3.13+99f9db8085
	   |-- fabric-sound-api-v1 1.0.8+75e9821185
	   |-- fabric-transfer-api-v1 2.1.15+ccd377ba85
	   \-- fabric-transitive-access-wideners-v1 2.3.1+40dc7a9485
	- fabricloader 0.14.19
	- java 17
	- m-tweaks 0.5.2-1.19.3
	   |-- cracker-util-analytics 0.4.2-1.19.3
	   |    |-- com_mixpanel_mixpanel-java 1.5.1
	   |    \-- org_json_json 20230227
	   |-- cracker-util-base 0.4.2-1.19.3
	   |    \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	   |-- cracker-util-content 0.4.2-1.19.3
	   |-- cracker-util-fake-world 0.4.2-1.19.3
	   \-- cracker-util-screen-particles 0.4.2-1.19.3
	- maptooltip 2.0.0
	- minecraft 1.19.3
[21:24:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Games/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:24:05] [main/INFO]: Compatibility level set to JAVA_17
[21:24:05] [main/INFO]: (TweaksMixinPlugin) Definitely up to a lot of good
[21:24:06] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[21:24:10] [main/INFO]: Building optimized datafixer
[21:24:14] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:24:15] [Render thread/INFO]: Setting user: Monty_McDonnell
[21:24:15] [Render thread/INFO]: (m-tweaks / BlockRegistry#register) BlockRegistry init complete!
[21:24:15] [Render thread/INFO]: (m-tweaks / ItemRegistry#register) ItemRegistry init complete!
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_anvil_minecart
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_note_block_minecart
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_jukebox_minecart
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_tnt_boat
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_furnace_boat
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_jukebox_boat
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_hopper_boat
[21:24:15] [Render thread/ERROR]: No data fixer registered for m_tweaks_flying_item
[21:24:15] [Render thread/INFO]: (m-tweaks / EntityTypeRegistry#register) EntityTypeRegistry init complete!
[21:24:15] [Render thread/INFO]: (m-tweaks / ResourceConditionRegistry#register) ResourceConditionRegistry init complete
[21:24:16] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[21:24:17] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[21:24:21] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Cloth Config v9, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, m-tweaks, Map Tooltip)
[21:24:24] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[21:24:24] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[21:24:24] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Lautsprecher (Realtek(R) Audio)
[21:24:24] [Render thread/INFO]: Sound engine started
[21:24:24] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[21:24:24] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/signs.png-atlas
[21:24:24] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[21:24:24] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[21:24:24] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[21:24:24] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[21:24:24] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[21:24:25] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[21:24:25] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[21:24:25] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[21:24:25] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[21:24:25] [Render thread/INFO]: (CrackerUtil / FakeWorld#<clinit>) CrackerUtil is creating a fake ClientWorld. Hold tight!
[21:24:33] [Render thread/INFO]: Loaded 7 recipes
[21:24:33] [Render thread/INFO]: Loaded 1215 advancements
[21:24:34] [Render thread/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 2.479 ms
[21:24:34] [Server thread/INFO]: Starting integrated minecraft server version 1.19.3
[21:24:34] [Server thread/INFO]: Generating keypair
[21:24:36] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:24:38] [Render thread/INFO]: Preparing spawn area: 0%
[21:24:38] [Render thread/INFO]: Preparing spawn area: 0%
[21:24:38] [Render thread/INFO]: Preparing spawn area: 0%
[21:24:38] [Render thread/INFO]: Preparing spawn area: 0%
[21:24:38] [Render thread/INFO]: Preparing spawn area: 0%
[21:24:39] [Worker-Bootstrap-10/INFO]: 4445 Datafixer optimizations took 28895 milliseconds
[21:24:39] [Render thread/INFO]: Preparing spawn area: 7%
[21:24:39] [Render thread/INFO]: Preparing spawn area: 75%
[21:24:40] [Server thread/INFO]: Loaded 1215 advancements
[21:24:40] [Server thread/INFO]: (m-tweaks / MiscUtil#generateRecipeAdvancements) finished hacking-in 0 recipe advancements
[21:24:40] [Render thread/INFO]: Time elapsed: 3367 ms
[21:24:40] [Server thread/INFO]: Changing view distance to 12, from 10
[21:24:40] [Server thread/INFO]: Changing simulation distance to 12, from 0
[21:24:41] [Server thread/INFO]: Monty_McDonnell[local:E:7f4ba3d4] logged in with entity id 78 at (458.6817622438234, 70.0625, -57.47815101847355)
[21:24:41] [Server thread/INFO]: Monty_McDonnell joined the game
[21:24:41] [Render thread/INFO]: Loaded 8 advancements
[21:24:46] [Server thread/INFO]: Saving and pausing game...
[21:24:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[21:24:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[21:24:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[21:24:56] [Render thread/INFO]: Loaded 9 advancements
[21:25:01] [Render thread/INFO]: Loaded 27 advancements
[21:25:56] [Render thread/INFO]: Loaded 28 advancements
[21:26:49] [Render thread/INFO]: Loaded 31 advancements
[21:27:43] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Unknown TooltipComponent
	at net.minecraft.class_5684.method_32663(class_5684.java:22) ~[client-intermediary.jar:?]
	at me.melontini.tweaks.client.TweaksClient.lambda$inGameTooltips$2(TweaksClient.java:111) ~[tweaks-0.5.2-1.19.3.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at me.melontini.tweaks.client.TweaksClient.lambda$inGameTooltips$3(TweaksClient.java:111) ~[tweaks-0.5.2-1.19.3.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-1.13.0+ad17775585-fa0066826ce00820.jar:?]
	at net.minecraft.class_329.handler$zho000$fabric-rendering-v1$render(class_329.java:1502) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:395) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:910) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.19-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
[21:27:43] [Server thread/INFO]: Stopping server
[21:27:43] [Server thread/INFO]: Saving players
[21:27:43] [Server thread/INFO]: Saving worlds
[21:27:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[21:27:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[21:27:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[21:27:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[21:27:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:27:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:27:45] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

### Mod Version

0.5.2

### Minecraft Version

- [ ] 1.18.2
- [ ] 1.19.x
- [X] 1.19.3

**Comment by melontini** [comment]
Fixed in 0.5.3
